name: vibe_check_aaa
description: "AAA Vibe-check App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.13.1

# 🔴 ส่วนนี้สำคัญมาก (อยู่นอก flutter:)
flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
